### ISSUE TITLE
Unable to cleanup releases

### ISSUE THREAD

**Issue by ryan-dyer-sp** [dev-drprasad/delete-older-releases#44]
I have a repo with ~10 releases and no pre-releases.  The tags and titles of the releases are the same and follow the format `v<major>.<minor>.<patch>` (semver).  My config is as such:
```
    - uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Output shows:
```

Run dev-drprasad/delete-older-releases@v0.3.3
  with:
    keep_latest: 5
    keep_min_download_counts: 0
    delete_expired_data: 0
    delete_prerelease_only: false
    github_rest_api_url: api.github.com
  env:
    GITHUB_TOKEN: ***
💬  no `repo` name given. fall-ing back to this repo
🌶  given `keep_min_download_counts` is 0, this will not enable the download count removal rule
🌶  given `delete_expired_data` is  0
😕  no active releases found. exiting...
```

I have content: write permissions on the GHA with an earlier step creating new releases with each push.

What am I missing?  Thanks!
