### ISSUE TITLE
Action doesn't trigger release/deleted events

### ISSUE THREAD

**Issue by ReenigneArcher** [dev-drprasad/delete-older-releases#48]
I'm not sure why, but this action doesn't appear to trigger release deleted events.

I am using a PAT with this action, so it "should" trigger new events, unlike using the default token provided to workflows.

Given the following sample workflow, the step does not run when a release is deleted by this action.

```yml
---
name: Sample

on:
  release:
    types: [created, edited, deleted]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.release.tag_name }}"
  cancel-in-progress: true

jobs:
  update-docs:
    env:
      TAG: ${{ github.event.release.tag_name }}
    if: >-
      !github.event.release.draft
    runs-on: ubuntu-latest
    steps:
      - name: Deleted release
        if: >-
          github.event_name == 'release' &&
          github.event.action == 'deleted'
        run: |
          echo "Release deleted"
```

Any ideas?

**Comment by thadguidry** [comment]
Maybe something to do with your release.draft exclusive?  I don't think a release draft is considered a "release event", but I could be wrong.  Github Action Docs to your rescue?
> Note: Workflows are not triggered for the created, edited, or deleted activity types for draft releases. When you create your release through the GitHub browser UI, your release may automatically be saved as a draft.

Reference:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

**Comment by thadguidry** [comment]
However, there are some other good GitHub Actions on the Marketplace that can handle dealing with draft releases quite well, and much better than you trying to understand the GitHub API's and allow you to just "get stuff done" much easier.

Here's one, but there are others that have "draft" releases support:
https://github.com/marketplace/actions/delete-draft-releases

Just do a search on the Marketplace for "release draft" or somesuch like I did here:
https://github.com/marketplace?query=release+draft

**Comment by ReenigneArcher** [comment]
This is not deleting draft releases, and I am specifically telling the workflow to ignore events that are for draft releases.

It was probably not clear, but I indicated that the "step" does not trigger, the workflow itself triggers, and other steps run, such as the following (when the release is edited of course).

```yml
      - name: Edited release
        if: >-
          github.event_name == 'release' &&
          github.event.action == 'edited'
        run: |
          echo "Release edited"
```

As a real example you can see here: https://github.com/LizardByte/Sunshine/actions/runs/9423696267/job/25962608366

This was an "edited" event.

The workflow should have triggered for a deleted event as well, but it only fired for created and edited. https://github.com/LizardByte/Sunshine/actions/workflows/update-docs.yml

![image](https://github.com/dev-drprasad/delete-older-releases/assets/42013603/bb050cdf-e378-4fc7-8d55-758fb0447226)


If I manually delete a pre-release, the workflow is triggered properly, so there is definitely a bug with this action and I believe you should re-open this.

![image](https://github.com/dev-drprasad/delete-older-releases/assets/42013603/3186bc13-1a0a-4216-8e97-db530906a147)
